from dataclasses import dataclass


@dataclass
class NotFoundExcTrans:
    Invoice = "فاکتور یافت نشد"
    ContractPayment = "پرداخت قرارداد یافت نشد"
    Contract = "قرارداد یافت نشد"
    ContractParty = "طرف قرارداد یافت نشد"
    User = "کاربر یافت نشد"
    SavedAds = "آگهی ذخیره شده یافت نشد"
    ContractStatus = "وضعیت قرارداد یافت نشد"
    PropertyRentContract = "قرارداد اجاره یافت نشد"
    Property = "ملک یافت نشد"
    BankAccount = "حساب بانکی مورد نظر یافت نشد"
    Organization = "سازمان یافت نشد"
    RefreshToken = "توکن یافت نشد"
    PropertyAd = "آگهی ملک یافت نشد"
    PropertyWantedAd = "آگهی ملک مورد نظر یافت نشد"
    SwapAd = "آگهی معاوضه یافت نشد"
    Cheque = "چک یافت نشد"
    ContractClause = "ماده قرارداد یافت نشد"
    Discount = "تخفیف یافت نشد"
    InvoiceItem = "آیتم فاکتور یافت نشد"
    Transaction = "تراکنش یافت نشد"
    WalletTransaction = "تراکنش کیف پول یافت نشد"
    Wallet = "کیف پول یافت نشد"
    City = "شهر یافت نشد"
    Province = "استان یافت نشد"
    District = "منطقه یافت نشد"
    File_ = "فایل یافت نشد"
    LandlordFile = "فایل مالک یافت نشد"
    RealtorFile = " فایل مشاور املاک یافت نشد"
    TenantFile = "فایل مستاجر یافت نشد"
    invoice_not_found = "فاکتور یافت نشد"
    payments_not_found = "پرداختی یافت نشد"
    deed_image_file_not_found = "تصویر سند یافت نشد"
    bank_account_not_found = "حساب بانکی مورد نظر یافت نشد"
    contract_parties_not_found = "طرفین قرارداد یافت نشد"
    contract_party_not_found = "طرف قرارداد یافت نشد"
    tenant_not_found = "مستاجر یافت نشد"
    landlord_not_found = "مالک یافت نشد"
    contract_not_found = "قرارداد یافت نشد"
    file_not_found = "فایل یافت نشد"
    contract_payment_not_found = "پرداخت قرارداد یافت نشد"
    PropertyRentContract = "قرارداد اجاره یافت نشد"
    commission_payment_not_found = "پرداخت کمیسیون یافت نشد"
    File = "فایل یافت نشد"
    prcontract_property_not_found = "اطلاعات ملک برای این قرارداد ثبت نشده است"
    contract_pdf_not_set = "فایل پی دی اف برای این قرارداد ثبت نشده است"
    payer_not_found = "پردازنده پرداخت یافت نشد"
    payee_not_found = "دریافت کننده پرداخت یافت نشد"
