from dataclasses import dataclass


@dataclass
class ProcessingExcTrans:
    deposit_amount_not_set = "مبلغ رهن تعیین نشده است"
    tenant_bank_account_not_set = "حساب بانکی مستاجر تعیین نشده است"
    landlord_deposit_bank_account_not_set = "حساب بانکی مالک برای رهن تعیین نشده است"
    monthly_rent_amount_not_set = "مبلغ اجاره تعیین نشده است"
    monthly_rent_amount_or_deposit_amount_not_set = "مبلغ اجاره یا مبلغ رهن تغیین نشده است"
    landlord_rent_bank_account_not_set = "حساب بانکی مالک برای اجاره تعیین نشده است"
    deposit_amount_not_match = "مبلغ رهن قرارداد با مجموع پرداخت‌های تعریف شده مطابقت ندارد"
    rent_amount_not_match = "مبلغ اجاره کل قرارداد با مجموع پرداخت‌های تعریف شده مطابقت ندارد"
    tracking_code_required_when_status_is_generated = "برای تغییر وضعیت به صادرشده، کدرهگیری را وارد کنید."
    calculations_failed = "محاسبات با خطا مواجه شد"
    contract_status_should_be_pending_admin_approval = "وضعیت قرارداد باید در انتظار تایید کارشناس حقوقی باشد"
    landlord_already_signed_contract = "مالک قبلا قرارداد را امضا کرده است"
    tenant_already_signed_contract = "مستاجر قبلا قرارداد را امضا کرده است"
    contract_cannot_changes_after_signing = "قرارداد پس از امضا قابل تغییر نیست"
    first_delete_existing_rent_payment = "ابتدا باید پرداخت اجاره موجود را حذف کنید"
    contract_information_not_set = "اطلاعات قرارداد تکمیل نشده است"
    incorrect_rent_payment = "پرداخت تعیین شده برای اجاره اشتباه است"
    payment_already_exists = "پرداخت قبلا ثبت شده است"
    contract_parties_not_set = "طرفین قرارداد تعیین نشده‌اند"
    payment_status_not_unpaid = "وضعیت پرداخت باید پرداخت نشده باشد"
    incorrect_payment_method = "روش پرداخت اشتباه است"
    tracking_code_status_cannot_be_changed = "وضعیت کد رهگیری قابل تغییر نیست"
    contract_status_must_be_admin_approved = "وضعیت قرارداد باید تایید شده توسط کارشناس حقوقی باشد"
    contract_status_must_be_admin_started = "قرارداد باید توسط مدیر ایجاد شده باشد."
    step_already_done = "این مرحله قبلا انجام شده است"
    verified_user_cannot_change_national_code_or_birth_date = (
        "کاربر تایید شده نمی‌تواند کد ملی یا تاریخ تولد خود را تغییر دهد"
    )
    invoice_not_created = "فاکتور ایجاد نشده است"
    payment_status_is_not_payer_claimed_to_have_paid = "وضعیت پرداخت باید `PAYER_CLAIMED_TO_HAVE_PAID` باشد"
    contract_is_rejected = "قرارداد رد شده است"
    contract_is_not_editable = "قرارداد غیر قابل ویرایش است"
    prcontract_property_was_deleted = "ملک مربوط به قرارداد اجاره حذف شده است"
    contract_party_already_added = "طرف مقابل در قرارداد قبلا اضافه شده است"
    both_parties_required_for_creating_payment = "برای ایجاد پرداخت جدید باید دو طرف قرارداد مشخص شده باشند"
    contract_clause_is_read_only = "این ماده قرارداد قابل ویرایش نیست"
    contract_clause_is_not_deletable = "این ماده قرارداد قابل حذف نیست"
    contract_status_should_be_edit_requested = "وضعیت قرارداد باید در حالت درخواست ویرایش باشد"
    file_is_not_public = "فایل مورد نظر عمومی نیست"
    iban_exists_with_different_owner_name = "حساب بانکی با این شماره شبا وجود دارد اما نام صاحب آن متفاوت است"
    contract_not_ready_for_pdf_generation = "قرارداد برای ایجاد فایل پی‌دی‌اف آماده نیست"
    failed_to_generate_pdf_file = "ایجاد فایل پی‌دی‌اف با خطا مواجه شد"
    some_steps_are_missing = "برخی از مراحل انجام نشده‌اند"
    after_paying_commission_cannot_delete_payment = (
        "پس از اینکه کمیسیون قرارداد پرداخت شد دیگر نمیشود پرداختی را حذف کرد"
    )
    action_order_incorrect = "ترتیب انجام عملیات نادرست است"
    contract_data_is_not_complete = "اطلاعات قرارداد کامل نیست"
    payment_already_finalized = "پرداخت قبلا نهایی شده است"
    pr_contract_cannot_be_deleted_after_some_steps = "بعد از انجام شدن برخی مراحل، امکان حذف قرارداد وجود ندارد"
