from dataclasses import dataclass


@dataclass
class ValidationExcTrans:
    invalid_payment_type = "نوع پرداخت نامعتبر است"
    exist_contract_party_type = "طرف قرارداد قبلا ثبت شده است"
    bank_account_not_provided = "حساب های طرف قرارداد مشخص نشده است."
    deposit_amount_should_be_positive = "مبلغ رهن باید مثبت باشد"
    mobile_and_national_code_dont_match = "کد ملی با شماره موبایل تطابق ندارد"
    birthdate_and_national_code_dont_match = "کدملی با تاریخ تولد تطابق ندارد"
    cant_create_condtract_for_a_dead_person = "صاحب اطلاعات وارد شده فوت کرده است"
    mobile_belongs_to_another_national_code = "شماره تلفن متعلق به کد ملی دیگری است"
    invalid_cheque_info = "اطلاعات وارد شده برای چک نادرست است"
    method_and_info_dont_match = "روش پرداخت با اطلاعات وارد شده همخوانی ندارد"
    invalid_value_for_percentage = "مقدار وارد شده (برای درصد) نامعتبر است"
    deposit_amount_exceeded = "جمع اقساط بیشتر از مبلغ رهن است"
    rent_amount_exceeded = "جمع اقساط وارده شده بیشتر از مبلغ کل اجاره است"
    contract_duration_is_partial = "بازه شروع و پایان قرارداد مضرب صحیحی از یک ماه نیست"
    end_date_should_be_after_start_date = "تاریخ پایان قرارداد باید بعد از تاریخ شروع باشد"
    handover_date_should_be_after_end_date = "تاریخ تحویل باید بعد از تاریخ پایان باشد"
    penalty_fee_should_be_positive = "مبلغ وجه التزام باید مثبت باشد"
    rent_amount_should_be_positive = "مبلغ اجاره باید مثبت باشد"
    verified_user_cannot_change_verified_info = "کاربر تایید شده نمی‌تواند اطلاعات تایید شده خود را تغییر دهد"
    verified_user_cannot_change_national_code = "کاربر تایید شده نمی‌تواند کد ملی خود را تغییر دهد"
    verified_user_cannot_change_birth_date = "کاربر تایید شده نمی‌تواند تاریخ تولد خود را تغییر دهد"
    cant_ask_for_verification_without_national_code_and_birth_date = (
        "شما نمیتوانید بدون کد ملی و تاریخ تولد درخواست احراز هویت کنید"
    )
    invalid_day_of_month = "روز وارد شده نامغتبر است"
    tracking_code_required_when_status_is_generated = "کد رهگیری مورد نیاز است"
    tracking_code_generation_date_required_when_status_is_generated = "تاریخ صدور کد رهگیری مورد نیاز است"
    national_code_does_not_belong_to_your_mobile_number = "کد ملی با شماره موبایل شما مطابقت ندارد"
    invalid_sort_field = "فیلد مورد نظر برای مرتب سازی نامعتبر است"
    invalid_sort_direction = "جهت مرتب سازی، نامعتبر است"
    invalid_property_parking_information = "اطلاعات پارکینگ نامعتبر است"
    invalid_property_landline_information = "اطلاعات تلفن ثابت نامعتبر است"
    invalid_property_storage_room_information = "اطلاعات انباری نامعتبر است"
    invalid_file_name = "نام فایل نامعتبر است"
    invalid_bucket_name = "نام باکت نامعتبر است"
    start_date_is_required = "تاریخ شروع رو وارد نکردی"
    end_date_is_required = "تاریخ پایان رو وارد نکردی"
    rent_amount_is_required = "مبلغ اجاره مورد نیاز است"
    rent_day_is_required = "روز پرداخت اجاره مورد نیاز است"
    contract_duration_must_be_more_than_one_month = "مدت قرارداد باید بیشتر از یک ماه باشد"
    mobile_invalid_characters = "شماره موبایل باید شامل اعداد باشد"
    mobile_invalid_length = "شماره موبایل باید ۱۱ رقمی باشد"
    mobile_invalid_prefix = "شماره موبایل باید با ۰۹ شروع شود"
    invalid_mobile_number = "شماره موبایل نامعتبر است"
    invalid_property_area = "مساحت ملک نامعتبر است"
    invalid_postal_code = "کد پستی نامعتبر است"
    national_code_invalid_characters = "کد ملی باید عدد باشد"
    national_code_invalid_length = "کد ملی باید ۱۰ رقمی باشد"
    invalid_national_code = "کد ملی نامعتبر است"
    birth_date_is_in_future = "تاریخ تولد نمی‌تواند در آینده باشد"
    amount_must_be_positive = "مبلغ باید مثبت باشد"
    invalid_property_build_year = "سال ساخت ملک نامعتبر است"
    contract_information_is_missing = "اطلاعات قرارداد کامل نیست"
    property_handover_date_should_be_before_end_date = "تاریخ تحویل ملک باید قبل از تاریخ پایان باشد"
    tracking_code_value_cannot_be_null = "مقدار کدرهگیری نمی‌تواند خالی باشد"
    invalid_value_for_caching = "مقدار وارد شده برای کش کردن نامعتبر است"
    wrong_contract_status = "وضعیت قرارداد نامعتبر است"
    tracking_code_already_updated = "کد پیگیری قبلا به روز شده است"
    contract_status_should_be_pending_admin_approval = "وضعیت قرارداد باید در حالت انتظار تایید ادمین باشد"
    contract_status_should_be_admin_approved = "ابتدا ادمین باید قرارداد را تایید کند"
    cheque_data_is_required_when_payment_type_is_cheque = "وقتی ورش پرداخت چک باشد، تمام اطلاعات چک باید وارد شود"
    sayaad_code_invalid_characters = "شناسه صیاد فقط باید شامل اعداد باشد"
    sayaad_code_length_should_be_16 = "شناسه صیاد باید ۱۶ رقمی باشد"
    payee_and_payer_cannot_be_the_same = "پرداخت کننده و دریافت کننده نمی‌توانند یکسان باشند"
    invalid_file = "فایل نامعتبر است"
    owner_user_id_is_required = "شناسه کاربر مالک ملک اجباری است"
    provide_max_rent_or_max_deposit_for_rent = "برای اجاره باید حداقل/حداکثر مبلغ رهن را  مشخص کنید"
    provide_sale_price_for_sale = "برای خرید و فروش باید مبلغ را مشخص کنید"
    not_enough_credit = "اعتبار کاربر کافی نمی‌باشد"
