from enum import Enum

from core.base.base_enum import BaseEnum


class ContractType(BaseEnum):
    PROPERTY_RENT = "PROPERTY_RENT"


class ClausesType(BaseEnum):
    DEFAULT_CLAUSES = "DEFAULT_CLAUSES"
    GUARANTEED_CLAUSES = "GUARANTEED_CLAUSES"


class PartyType(BaseEnum):
    LANDLORD = "LANDLORD"
    TENANT = "TENANT"


class PaymentSide(BaseEnum):
    PAYER = "PAYER"
    PAYEE = "PAYEE"


class ContractStatus(BaseEnum):
    ADMIN_STARTED = "ADMIN_STARTED"
    #
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PENDING_COMMISSION = "PENDING_COMMISSION"
    EDIT_REQUESTED = "EDIT_REQUESTED"
    PARTY_REJECTED = "PARTY_REJECTED"
    #
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    # ADMIN_APPROVED = "ADMIN_APPROVED" # Using COMPLETED instead
    ADMIN_REJECTED = "ADMIN_REJECTED"
    #
    COMPLETED = "COMPLETED"
    REVOKED = "REVOKED"
    PDF_GENERATED = "PDF_GENERATED"
    PDF_GENERATING_FAILED = "PDF_GENERATING_FAILED"


class PRContractStep(BaseEnum):
    # # Common Steps # #
    DATES_AND_PENALTIES = "DATES_AND_PENALTIES"
    MONTHLY_RENT = "MONTHLY_RENT"
    RENT_PAYMENT = "RENT_PAYMENT"
    DEPOSIT = "DEPOSIT"
    ADD_COUNTER_PARTY = "ADD_COUNTER_PARTY"
    DEPOSIT_PAYMENT = "DEPOSIT_PAYMENT"
    # # Tenant Specific Steps # #
    TENANT_INFORMATION = "TENANT_INFORMATION"
    TENANT_APPROVE = "TENANT_APPROVE"
    TENANT_SIGNATURE = "TENANT_SIGNATURE"
    TENANT_COMMISSION = "TENANT_COMMISSION"
    TENANT_REJECTED = "TENANT_REJECTED"
    TENANT_EDIT_REQUEST = "TENANT_EDIT_REQUEST"
    # # Landlord Specific Steps # #
    LANDLORD_INFORMATION = "LANDLORD_INFORMATION"
    PROPERTY_SPECIFICATIONS = "PROPERTY_SPECIFICATIONS"
    PROPERTY_DETAILS = "PROPERTY_DETAILS"
    PROPERTY_FACILITIES = "PROPERTY_FACILITIES"
    LANDLORD_SIGNATURE = "LANDLORD_SIGNATURE"
    LANDLORD_COMMISSION = "LANDLORD_COMMISSION"
    LANDLORD_REJECTED = "LANDLORD_REJECTED"
    LANDLORD_EDIT_REQUEST = "LANDLORD_EDIT_REQUEST"
    # # # # # # # # # # # # # # # # # #
    ADMIN_APPROVE = "ADMIN_APPROVE"
    ADMIN_REJECT = "ADMIN_REJECT"
    #
    TRACKING_CODE_REQUESTED = "TRACKING_CODE_REQUESTED"
    TRACKING_CODE_DELIVERED = "TRACKING_CODE_DELIVERED"
    TRACKING_CODE_FAILED = "TRACKING_CODE_FAILED"


class PRContractState(BaseEnum):
    TENANT_REJECTED = "TENANT_REJECTED"
    TENANT_EDIT_REQUEST = "TENANT_EDIT_REQUEST"
    LANDLORD_REJECTED = "LANDLORD_REJECTED"
    LANDLORD_EDIT_REQUEST = "LANDLORD_EDIT_REQUEST"
    ADMIN_REJECTED = "ADMIN_REJECTED"
    #
    DRAFT = "DRAFT"
    PENDING_TENANT_APPROVAL = "PENDING_TENANT_APPROVAL"
    PENDING_TENANT_INFORMATION = "PENDING_TENANT_INFORMATION"
    PENDING_LANDLORD_INFORMATION = "PENDING_LANDLORD_INFORMATION"
    #
    PENDING_LANDLORD_SIGNATURE = "PENDING_LANDLORD_SIGNATURE"
    PENDING_TENANT_SIGNATURE = "PADDING_TENANT_SIGNATURE"
    #
    PENDING_PAYING_COMMISSION = "PENDING_PAYING_COMMISSION"
    PENDING_LANDLORD_COMMISSION = "PENDING_LANDLORD_COMMISSION"
    PENDING_TENANT_COMMISSION = "PENDING_TENANT_COMMISSION"
    #
    PENDING_ADMIN_APPROVAL = "PENDING_ADMIN_APPROVAL"
    PENDING_TRACKING_CODE_REQUEST = "PENDING_TRACKING_CODE"
    PENDING_TRACKING_CODE_DELIVERY = "PENDING_TRACKING_CODE_DELIVERY"
    TRACKING_CODE_DELIVERED = "TRACKING_CODE_DELIVERED"
    PDF_GENERATED = "PDF_GENERATED"


class PaymentMethod(BaseEnum):
    CASH = "CASH"
    CHEQUE = "CHEQUE"


class PaymentStatus(BaseEnum):
    PAID = "PAID"
    UNPAID = "UNPAID"
    OVERDUE = "OVERDUE"
    CANCELLED = "CANCELLED"

    # payer has asserted that they made the payment but payee has not confirmed receipt.
    PAYER_CLAIMED_TO_HAVE_PAID = "PAYER_CLAIMED_TO_HAVE_PAID"

    # payee has received and confirmed the payment.
    PAYEE_CONFIRMED_RECEIPT = "PAYEE_CONFIRMED_RECEIPT"

    # payee denies having received the payment
    PAYEE_DENIED_RECEIPT = "PAYEE_DENIED_RECEIPT"


class PaymentType(BaseEnum):
    RENT = "RENT"
    DEPOSIT = "DEPOSIT"
    COMMISSION = "COMMISSION"
    WALLET_CHARGE = "WALLET_CHARGE"
    CUSTOM_PAYMENT = "CUSTOM_PAYMENT"
    WALLET_WITHDRAW = "WALLET_WITHDRAW"
    ERNEST_MONEY = "ERNEST_MONEY"
    REFUND = "REFUND"


class ChequeCategory(BaseEnum):
    SALARY = "SALARY"
    INSURANCE = "INSURANCE"
    HEALTH_CARE = "HEALTH_CARE"
    INVESTMENT = "INVESTMENT"
    FOREIGN_EXCHANGE = "FOREIGN_EXCHANGE"
    LOAN = "LOAN"
    RETIREMENT = "RETIREMENT"
    MOVABLE_PROPERTY = "MOVABLE_PROPERTY"
    IMMOVABLE_PROPERTY = "IMMOVABLE_PROPERTY"
    CASH_MANAGEMENT = "CASH_MANAGEMENT"
    CUSTOMS_DUTIES = "CUSTOMS_DUTIES"
    TAX_DUTIES = "TAX_DUTIES"
    GOVERNMENTAL_SERVICES = "GOVERNMENTAL_SERVICES"
    FACILITIES = "FACILITIES"
    BAIL_DEPOSIT = "BAIL_DEPOSIT"
    DAILY_EXPENSES = "DAILY_EXPENSES"
    CHARITY = "CHARITY"
    GOODS_PURCHASE = "GOODS_PURCHASE"
    SERVICES_PURCHASE = "SERVICES_PURCHASE"


class ChequePayeeType(BaseEnum):
    INDIVIDUAL = "INDIVIDUAL"  # شخص حقیقی
    LEGAL_ENTITY = "LEGAL_ENTITY"  # شخص حقوقی
    FOREIGN_NATIONALS = "FOREIGN_NATIONALS"  # اتباع خارجی


class ChequeStatus(BaseEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PRContractPaymentType(BaseEnum):
    DEPOSIT = "DEPOSIT"
    RENT = "RENT"

    @property
    def type(self) -> PaymentType:
        return PaymentType.resolve(self.value)


class TrackingCodeStatus(BaseEnum):
    NOT_GENERATED = "NOT_GENERATED"
    REQUESTED = "REQUESTED"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"


class SignatureType(BaseEnum):
    OTP = "OTP"


class PRCPartyType(BaseEnum):
    LANDLORD = "LANDLORD"
    TENANT = "TENANT"


class ContractColor(BaseEnum):
    RED = "RED"
    GREEN = "GREEN"
    PURPLE = "PURPLE"


class InvoiceItems(Enum):
    TAX = (1, "*", 0.1)
    DELIVERY = (2, "+", 0)
    TRACKING_CODE = (3, "+", 50000)
    TEHRAN_BUYING_COMMISSION = (4, "*", 0.01)  # 1% of the whole price
    PROVINCES_BUYING_COMMISSION = (5, "*", 0.005)  # 0.5% of the whole price
    RENT_COMMISSION = (6, "*", 0.3)  # 30% of the rent amount
    MORTGAGE_COMMISSION = (
        7,
        "*",
        0.006,
    )  # 6000 toman per 1-milion unit of mortgage amount (0.6%)

    def __init__(self, id, mathematical_operator, weight):
        self.id = id
        self.weight = weight
        self.mathematical_operator = mathematical_operator
