"""add tenant_family_members_count and remove unused fields

Revision ID: 1d470ef4fc82
Revises: fb03f0330df5
Create Date: 2024-10-08 16:35:06.854199

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d470ef4fc82"
down_revision: Union[str, None] = "fb03f0330df5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "users", "files_", ["avatar_file_id"], ["id"], source_schema="account", referent_schema="shared"
    )
    op.alter_column("cheques", "image_file_id", existing_type=sa.BIGINT(), nullable=True, schema="contract")
    op.create_index(
        op.f("ix_contract_cheques_image_file_id"), "cheques", ["image_file_id"], unique=False, schema="contract"
    )
    op.create_foreign_key(
        None, "cheques", "files_", ["image_file_id"], ["id"], source_schema="contract", referent_schema="shared"
    )
    op.drop_column("contract_parties", "is_primary", schema="contract")
    op.create_index(
        op.f("ix_contract_contracts_pdf_file_id"), "contracts", ["pdf_file_id"], unique=False, schema="contract"
    )
    op.create_foreign_key(
        None, "contracts", "files_", ["pdf_file_id"], ["id"], source_schema="contract", referent_schema="shared"
    )
    op.drop_column("contracts", "completed_at", schema="contract")
    op.drop_column("contracts", "key", schema="contract")
    op.drop_column("contracts", "owner_party_type", schema="contract")
    op.drop_column("contracts", "date", schema="contract")
    op.add_column(
        "property_rent_contracts",
        sa.Column("tenant_family_members_count", sa.Integer(), nullable=True),
        schema="contract",
    )
    op.create_foreign_key(
        None,
        "property_rent_contracts",
        "files_",
        ["pdf_file_id"],
        ["id"],
        source_schema="contract",
        referent_schema="shared",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "property_rent_contracts", schema="contract", type_="foreignkey")
    op.drop_column("property_rent_contracts", "tenant_family_members_count", schema="contract")
    op.add_column("contracts", sa.Column("date", sa.DATE(), autoincrement=False, nullable=True), schema="contract")
    op.add_column(
        "contracts", sa.Column("owner_party_type", sa.VARCHAR(), autoincrement=False, nullable=False), schema="contract"
    )
    op.add_column(
        "contracts", sa.Column("key", sa.VARCHAR(length=6), autoincrement=False, nullable=True), schema="contract"
    )
    op.add_column(
        "contracts", sa.Column("completed_at", sa.DATE(), autoincrement=False, nullable=True), schema="contract"
    )
    op.drop_constraint(None, "contracts", schema="contract", type_="foreignkey")
    op.drop_index(op.f("ix_contract_contracts_pdf_file_id"), table_name="contracts", schema="contract")
    op.add_column(
        "contract_parties",
        sa.Column("is_primary", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="contract",
    )
    op.drop_constraint(None, "cheques", schema="contract", type_="foreignkey")
    op.drop_index(op.f("ix_contract_cheques_image_file_id"), table_name="cheques", schema="contract")
    op.alter_column("cheques", "image_file_id", existing_type=sa.BIGINT(), nullable=False, schema="contract")
    op.drop_constraint(None, "users", schema="account", type_="foreignkey")
    # ### end Alembic commands ###
