"""add new files table

Revision ID: 1ecd4aef98bc
Revises: a72e9f8c42ae
Create Date: 2024-09-16 11:12:56.949758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ecd4aef98bc"
down_revision: Union[str, None] = "a72e9f8c42ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files_",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("access", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.add_column(
        "properties",
        sa.Column("elevator", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        schema="shared",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "elevator", schema="shared")
    op.drop_table("files_", schema="shared")
    # ### end Alembic commands ###
