"""contract_desc

Revision ID: 2752fd04aabc
Revises: d04b5c4da764
Create Date: 2025-11-10 11:41:01.251722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2752fd04aabc'
down_revision: Union[str, None] = 'd04b5c4da764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_descriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='contract'
    )
    op.create_index(op.f('ix_contract_contract_descriptions_contract_id'), 'contract_descriptions', ['contract_id'], unique=False, schema='contract')
    op.create_index(op.f('ix_contract_contract_descriptions_created_by'), 'contract_descriptions', ['created_by'], unique=False, schema='contract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_contract_descriptions_created_by'), table_name='contract_descriptions', schema='contract')
    op.drop_index(op.f('ix_contract_contract_descriptions_contract_id'), table_name='contract_descriptions', schema='contract')
    op.drop_table('contract_descriptions', schema='contract')
    # ### end Alembic commands ###
