"""user-call

Revision ID: 27c874a2744a
Revises: b5f1d6844070
Create Date: 2025-10-06 16:49:35.252941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c874a2744a'
down_revision: Union[str, None] = 'b5f1d6844070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='account'
    )
    op.create_index(op.f('ix_account_user_calls_created_by'), 'user_calls', ['created_by'], unique=False, schema='account')
    op.create_index(op.f('ix_account_user_calls_user_id'), 'user_calls', ['user_id'], unique=False, schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_calls_user_id'), table_name='user_calls', schema='account')
    op.drop_index(op.f('ix_account_user_calls_created_by'), table_name='user_calls', schema='account')
    op.drop_table('user_calls', schema='account')
    # ### end Alembic commands ###
