"""Change price columns to BigInteger

Revision ID: 32a684acc9c4
Revises: dbe8a5bf59f5
Create Date: 2024-10-05 10:37:38.911923

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32a684acc9c4"
down_revision: Union[str, None] = "dbe8a5bf59f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "property_ads",
        "deposit_amount",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_ads",
        "rent_amount",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_ads",
        "sale_price",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "max_deposit",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "max_rent",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "sale_price",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "swap_ads",
        "price",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
        schema="advertisement",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "swap_ads",
        "price",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "sale_price",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "max_rent",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_wanted_ads",
        "max_deposit",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_ads",
        "sale_price",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_ads",
        "rent_amount",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    op.alter_column(
        "property_ads",
        "deposit_amount",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="advertisement",
    )
    # ### end Alembic commands ###
