"""extrafields

Revision ID: 369951bee0ac
Revises: 20028cd307bc
Create Date: 2025-08-07 12:10:27.697420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "369951bee0ac"
down_revision: Union[str, None] = "20028cd307bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("landlord_files", sa.Column("second_mobile", sa.String(), nullable=True), schema="crm")
    op.add_column("landlord_files", sa.Column("parking_type", sa.String(), nullable=True), schema="crm")
    op.add_column("landlord_files", sa.Column("parking_count", sa.Integer(), nullable=True), schema="crm")
    op.add_column("landlord_files", sa.Column("visit_time", sa.String(), nullable=True), schema="crm")
    op.add_column("landlord_files", sa.Column("evacuation_date", sa.Date(), nullable=True), schema="crm")
    op.drop_column("landlord_files", "parking", schema="crm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "landlord_files", sa.Column("parking", sa.BOOLEAN(), autoincrement=False, nullable=True), schema="crm"
    )
    op.drop_column("landlord_files", "evacuation_date", schema="crm")
    op.drop_column("landlord_files", "visit_time", schema="crm")
    op.drop_column("landlord_files", "parking_count", schema="crm")
    op.drop_column("landlord_files", "parking_type", schema="crm")
    op.drop_column("landlord_files", "second_mobile", schema="crm")
    op.add_column(
        "contract_parties",
        sa.Column("is_primary", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        schema="contract",
    )
    op.add_column(
        "contract_parties",
        sa.Column(
            "party_share",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        schema="contract",
    )
    op.add_column(
        "contract_parties", sa.Column("company_id", sa.BIGINT(), autoincrement=False, nullable=True), schema="contract"
    )
    op.create_foreign_key(
        op.f("contract_parties_company_id_fkey"),
        "contract_parties",
        "companies",
        ["company_id"],
        ["id"],
        source_schema="contract",
        referent_schema="account",
    )
    op.create_unique_constraint(
        op.f("uq_contract_user"), "contract_parties", ["contract_id", "user_id"], schema="contract"
    )
    op.create_index(
        op.f("ix_contract_contract_parties_company_id"),
        "contract_parties",
        ["company_id"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("national_ID", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("registration_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("companies_pkey")),
        sa.UniqueConstraint("national_ID", name=op.f("companies_national_ID_key")),
        schema="account",
    )
    # ### end Alembic commands ###
