"""color

Revision ID: 39aae4e49c1f
Revises: 2752fd04aabc
Create Date: 2025-11-19 16:31:21.230083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39aae4e49c1f'
down_revision: Union[str, None] = '2752fd04aabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_rent_contracts', sa.Column('color', sa.String(), nullable=True), schema='contract')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_rent_contracts', 'color', schema='contract')
    # ### end Alembic commands ###
