"""add is guaranteed to prcontracts

Revision ID: 3b7e994d2330
Revises: 32a684acc9c4
Create Date: 2024-10-07 10:26:07.419643

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b7e994d2330"
down_revision: Union[str, None] = "32a684acc9c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "property_rent_contracts",
        sa.Column("is_guaranteed", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        schema="contract",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("property_rent_contracts", "is_guaranteed", schema="contract")
    # ### end Alembic commands ###
