"""property_wanted_ad_title

Revision ID: 3bf6ac81d746
Revises: 4415ce15020e
Create Date: 2025-05-27 11:13:45.866671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf6ac81d746'
down_revision: Union[str, None] = '4415ce15020e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_wanted_ads', sa.Column('title', sa.String(length=50), nullable=True), schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_wanted_ads', 'title', schema='advertisement')
    # ### end Alembic commands ###
