"""unique_discount_code

Revision ID: 3d22e77410b2
Revises: cefc5a97010c
Create Date: 2025-05-31 17:35:34.120336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d22e77410b2'
down_revision: Union[str, None] = 'cefc5a97010c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'discounts', ['code'], schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discounts', schema='financial', type_='unique')
    # ### end Alembic commands ###
