"""update_alembic

Revision ID: 4415ce15020e
Revises: 7a1c0f30dace
Create Date: 2025-05-26 20:13:21.676682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4415ce15020e'
down_revision: Union[str, None] = '7a1c0f30dace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_contract_clauses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('clauses_type', sa.String(), nullable=False),
    sa.Column('clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clauses_backup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_type', 'clauses_type', name='uq_contract_type_clauses_type'),
    schema='contract'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_contract_clauses', schema='contract')
    # ### end Alembic commands ###
