"""remove_pwd_title

Revision ID: 517e607242fa
Revises: 3bf6ac81d746
Create Date: 2025-05-27 14:06:39.312719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e607242fa'
down_revision: Union[str, None] = '3bf6ac81d746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_wanted_ads', 'title', schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_wanted_ads', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='advertisement')
    # ### end Alembic commands ###
