"""city-district

Revision ID: 581802635076
Revises: 59ba4c567083
Create Date: 2025-08-07 12:59:28.608396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '581802635076'
down_revision: Union[str, None] = '59ba4c567083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crm_landlord_files_city_id'), 'landlord_files', ['city_id'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_landlord_files_district_id'), 'landlord_files', ['district_id'], unique=False, schema='crm')
    op.create_foreign_key(None, 'landlord_files', 'cities', ['city_id'], ['id'], source_schema='crm', referent_schema='shared')
    op.create_foreign_key(None, 'landlord_files', 'districts', ['district_id'], ['id'], source_schema='crm', referent_schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landlord_files', schema='crm', type_='foreignkey')
    op.drop_constraint(None, 'landlord_files', schema='crm', type_='foreignkey')
    op.drop_index(op.f('ix_crm_landlord_files_district_id'), table_name='landlord_files', schema='crm')
    op.drop_index(op.f('ix_crm_landlord_files_city_id'), table_name='landlord_files', schema='crm')
    op.add_column('contract_parties', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='contract')
    op.add_column('contract_parties', sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='contract')
    op.add_column('contract_parties', sa.Column('party_share', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='contract')
    op.create_foreign_key(op.f('contract_parties_company_id_fkey'), 'contract_parties', 'companies', ['company_id'], ['id'], source_schema='contract', referent_schema='account')
    op.create_unique_constraint(op.f('uq_contract_user'), 'contract_parties', ['contract_id', 'user_id'], schema='contract')
    op.create_index(op.f('ix_contract_contract_parties_company_id'), 'contract_parties', ['company_id'], unique=False, schema='contract')
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('national_ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey')),
    sa.UniqueConstraint('national_ID', name=op.f('companies_national_ID_key')),
    schema='account'
    )
    # ### end Alembic commands ###
