"""call-type

Revision ID: 58a2fd4e200e
Revises: d9b36a285def
Create Date: 2025-10-18 14:08:07.245105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58a2fd4e200e"
down_revision: Union[str, None] = "d9b36a285def"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_calls", sa.Column("type", sa.String(), nullable=False, server_default="INCOMING"), schema="account"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_calls", "type", schema="account")
    # ### end Alembic commands ###
