"""call_status

Revision ID: 59ba4c567083
Revises: 369951bee0ac
Create Date: 2025-08-07 12:22:49.612597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ba4c567083'
down_revision: Union[str, None] = '369951bee0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_calls', sa.Column('status', sa.String(), nullable=True), schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_calls', 'status', schema='crm')
    op.add_column('contract_parties', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='contract')
    op.add_column('contract_parties', sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='contract')
    op.add_column('contract_parties', sa.Column('party_share', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='contract')
    op.create_foreign_key(op.f('contract_parties_company_id_fkey'), 'contract_parties', 'companies', ['company_id'], ['id'], source_schema='contract', referent_schema='account')
    op.create_unique_constraint(op.f('uq_contract_user'), 'contract_parties', ['contract_id', 'user_id'], schema='contract')
    op.create_index(op.f('ix_contract_contract_parties_company_id'), 'contract_parties', ['company_id'], unique=False, schema='contract')
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('national_ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey')),
    sa.UniqueConstraint('national_ID', name=op.f('companies_national_ID_key')),
    schema='account'
    )
    # ### end Alembic commands ###
