"""change foregin keys to new files table

Revision ID: 5b3f21391c7a
Revises: a9cf95bd03d9
Create Date: 2024-09-18 14:02:10.209126

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b3f21391c7a"
down_revision: Union[str, None] = "a9cf95bd03d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("organizations_avatar_file_id_fkey", "organizations", schema="account", type_="foreignkey")
    # op.create_foreign_key(
    #     None, "organizations", "files_", ["avatar_file_id"], ["id"], source_schema="account", referent_schema="shared"
    # )
    op.drop_constraint(
        "property_rent_contracts_pdf_file_id_fkey", "property_rent_contracts", schema="contract", type_="foreignkey"
    )
    # op.create_foreign_key(
    #     None,
    #     "property_rent_contracts",
    #     "files_",
    #     ["pdf_file_id"],
    #     ["id"],
    #     source_schema="contract",
    #     referent_schema="shared",
    # )
    op.drop_table("files", schema="shared")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "property_rent_contracts", schema="contract", type_="foreignkey")
    op.create_foreign_key(
        "property_rent_contracts_pdf_file_id_fkey",
        "property_rent_contracts",
        "files",
        ["pdf_file_id"],
        ["id"],
        source_schema="contract",
        referent_schema="shared",
    )
    op.drop_constraint(None, "organizations", schema="account", type_="foreignkey")
    op.create_foreign_key(
        "organizations_avatar_file_id_fkey",
        "organizations",
        "files",
        ["avatar_file_id"],
        ["id"],
        source_schema="account",
        referent_schema="shared",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("bucket", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("file_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mime_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("is_used", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="files_pkey"),
        schema="shared",
    )
    # ### end Alembic commands ###
