"""add type to file_ table

Revision ID: 6b940c144af4
Revises: 996fca1ef172
Create Date: 2024-09-18 12:41:22.422678

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b940c144af4"
down_revision: Union[str, None] = "996fca1ef172"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files_", sa.Column("type", sa.String(), nullable=True), schema="shared")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files_", "type", schema="shared")
    # ### end Alembic commands ###
