"""contract created by

Revision ID: 6c1309b9061e
Revises: 7470fa02a42c
Create Date: 2025-10-29 14:06:00.149851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1309b9061e'
down_revision: Union[str, None] = '7470fa02a42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('created_by', sa.BigInteger(), nullable=False, server_default="123456789"), schema='contract')
    op.create_index(op.f('ix_contract_contracts_created_by'), 'contracts', ['created_by'], unique=False, schema='contract')
    op.create_foreign_key(None, 'contracts', 'users', ['created_by'], ['id'], source_schema='contract', referent_schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', schema='contract', type_='foreignkey')
    op.drop_index(op.f('ix_contract_contracts_created_by'), table_name='contracts', schema='contract')
    op.drop_column('contracts', 'created_by', schema='contract')
    # ### end Alembic commands ###
