"""eitaa_user_ud

Revision ID: 7470fa02a42c
Revises: 58a2fd4e200e
Create Date: 2025-10-19 10:28:52.692116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7470fa02a42c'
down_revision: Union[str, None] = '58a2fd4e200e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('eitaa_user_id', sa.String(), nullable=True), schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'eitaa_user_id', schema='account')
    # ### end Alembic commands ###
