"""added description column to visit requests

Revision ID: 805fb1823714
Revises: cf67b91f1ba4
Create Date: 2024-09-25 15:07:47.836596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805fb1823714'
down_revision: Union[str, None] = 'cf67b91f1ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('description', sa.String(), nullable=True), schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'description', schema='advertisement')
    # ### end Alembic commands ###
