"""add deleted at to new files table

Revision ID: 996fca1ef172
Revises: 1ecd4aef98bc
Create Date: 2024-09-16 16:24:39.202293

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "996fca1ef172"
down_revision: Union[str, None] = "1ecd4aef98bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files_", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True), schema="shared")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files_", "deleted_at", schema="shared")
    # ### end Alembic commands ###
