"""remove organizations, permissions, role_permissions

Revision ID: 9c00d55df629
Revises: 805fb1823714
Create Date: 2024-10-01 13:07:16.817111

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c00d55df629"
down_revision: Union[str, None] = "805fb1823714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_permissions", schema="account")
    op.drop_index("ix_account_permissions_name", table_name="permissions", schema="account")
    op.drop_table("permissions", schema="account")
    op.drop_index("ix_account_organizations_user_id", table_name="organizations", schema="account")
    op.drop_index("ix_account_organizations_user_mobile", table_name="organizations", schema="account")
    op.drop_table("organizations", schema="account")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("user_mobile", sa.VARCHAR(length=11), autoincrement=False, nullable=False),
        sa.Column("user_is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("postal_code", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("avatar_file_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["avatar_file_id"], ["shared.files_.id"], name="organizations_avatar_file_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["account.users.id"], name="organizations_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="organizations_pkey"),
        schema="account",
    )
    op.create_index(
        "ix_account_organizations_user_mobile", "organizations", ["user_mobile"], unique=False, schema="account"
    )
    op.create_index("ix_account_organizations_user_id", "organizations", ["user_id"], unique=False, schema="account")
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("permission_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["account.permissions.id"], name="role_permissions_permission_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="role_permissions_pkey"),
        sa.UniqueConstraint("user_role", "permission_id", name="uq_role_permissions"),
        schema="account",
    )
    op.create_index(
        "ix_account_role_permissions_permission_id",
        "role_permissions",
        ["permission_id"],
        unique=False,
        schema="account",
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="permissions_pkey"),
        schema="account",
    )
    op.create_index("ix_account_permissions_name", "permissions", ["name"], unique=True, schema="account")
    # ### end Alembic commands ###
