"""extra_fields

Revision ID: a0c2d3cc91da
Revises: a59f02a2c7a3
Create Date: 2025-08-03 11:26:00.441377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c2d3cc91da'
down_revision: Union[str, None] = 'a59f02a2c7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord_files', sa.Column('property_characteristics', sa.ARRAY(sa.String()), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('occupancy_status', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('floor', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('units_per_floor', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('total_floors', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('label_ids', sa.ARRAY(sa.BigInteger()), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('latitude', sa.Float(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('longitude', sa.Float(), nullable=True), schema='crm')
    op.alter_column('realtor_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtor_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='crm')
    op.drop_column('landlord_files', 'longitude', schema='crm')
    op.drop_column('landlord_files', 'latitude', schema='crm')
    op.drop_column('landlord_files', 'label_ids', schema='crm')
    op.drop_column('landlord_files', 'total_floors', schema='crm')
    op.drop_column('landlord_files', 'units_per_floor', schema='crm')
    op.drop_column('landlord_files', 'floor', schema='crm')
    op.drop_column('landlord_files', 'occupancy_status', schema='crm')
    op.drop_column('landlord_files', 'property_characteristics', schema='crm')
    op.add_column('contract_parties', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='contract')
    op.add_column('contract_parties', sa.Column('party_share', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False), schema='contract')
    op.add_column('contract_parties', sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='contract')
    op.create_foreign_key(op.f('contract_parties_company_id_fkey'), 'contract_parties', 'companies', ['company_id'], ['id'], source_schema='contract', referent_schema='account')
    op.create_unique_constraint(op.f('uq_contract_user'), 'contract_parties', ['contract_id', 'user_id'], schema='contract')
    op.create_index(op.f('ix_contract_contract_parties_company_id'), 'contract_parties', ['company_id'], unique=False, schema='contract')
    op.create_table('companies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('national_ID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey')),
    sa.UniqueConstraint('national_ID', name=op.f('companies_national_ID_key')),
    schema='account'
    )
    # ### end Alembic commands ###
