"""crm

Revision ID: a115009334fb
Revises: c6f612c1d7b5
Create Date: 2025-07-30 15:02:14.126364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a115009334fb'
down_revision: Union[str, None] = 'c6f612c1d7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_labels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_table('file_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_table('file_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_table('file_calls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_file_calls_created_by'), 'file_calls', ['created_by'], unique=False, schema='crm')
    op.create_table('file_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_file_texts_created_by'), 'file_texts', ['created_by'], unique=False, schema='crm')
    op.create_table('landlord_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=False),
    sa.Column('file_source_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('rent', sa.BigInteger(), nullable=True),
    sa.Column('deposit', sa.BigInteger(), nullable=True),
    sa.Column('dynamic_amount', sa.Boolean(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('bathroom', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('heating', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cooling', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('flooring', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_tenants', sa.Integer(), nullable=True),
    sa.Column('other_facilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('storage', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('renovated', sa.Boolean(), nullable=True),
    sa.Column('property_image_file_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('landlord_agreed_to_remove_ad', sa.Boolean(), nullable=True),
    sa.Column('reason_for_not_removing_ad', sa.Text(), nullable=True),
    sa.Column('divar_ad_link', sa.String(), nullable=True),
    sa.Column('eitaa_ad_link', sa.String(), nullable=True),
    sa.Column('ad_title', sa.String(), nullable=True),
    sa.Column('published_on_amline', sa.Boolean(), nullable=True),
    sa.Column('amline_ad_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['file_source_id'], ['crm.file_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_landlord_files_assigned_to'), 'landlord_files', ['assigned_to'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_landlord_files_created_by'), 'landlord_files', ['created_by'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_landlord_files_file_source_id'), 'landlord_files', ['file_source_id'], unique=False, schema='crm')
    op.create_table('realtor_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=False),
    sa.Column('file_source_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['file_source_id'], ['crm.file_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_realtor_files_assigned_to'), 'realtor_files', ['assigned_to'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_realtor_files_created_by'), 'realtor_files', ['created_by'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_realtor_files_file_source_id'), 'realtor_files', ['file_source_id'], unique=False, schema='crm')
    op.create_table('tenant_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger(), nullable=False),
    sa.Column('file_source_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('family_members_count', sa.Integer(), nullable=True),
    sa.Column('children_ages_description', sa.Text(), nullable=True),
    sa.Column('tenant_deadline', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('rent', sa.BigInteger(), nullable=True),
    sa.Column('deposit', sa.BigInteger(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('district_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('address_description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('bathroom', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('heating', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cooling', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('flooring', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('other_facilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('storage', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('ad_title', sa.String(), nullable=True),
    sa.Column('eitaa_ad_link', sa.String(), nullable=True),
    sa.Column('published_on_amline', sa.Boolean(), nullable=True),
    sa.Column('amline_ad_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['file_source_id'], ['crm.file_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_tenant_files_assigned_to'), 'tenant_files', ['assigned_to'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_tenant_files_created_by'), 'tenant_files', ['created_by'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_tenant_files_file_source_id'), 'tenant_files', ['file_source_id'], unique=False, schema='crm')
    op.create_table('entity_change_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shared'
    )
    op.create_index(op.f('ix_shared_entity_change_logs_user_id'), 'entity_change_logs', ['user_id'], unique=False, schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_entity_change_logs_user_id'), table_name='entity_change_logs', schema='shared')
    op.drop_table('entity_change_logs', schema='shared')
    op.drop_index(op.f('ix_crm_tenant_files_file_source_id'), table_name='tenant_files', schema='crm')
    op.drop_index(op.f('ix_crm_tenant_files_created_by'), table_name='tenant_files', schema='crm')
    op.drop_index(op.f('ix_crm_tenant_files_assigned_to'), table_name='tenant_files', schema='crm')
    op.drop_table('tenant_files', schema='crm')
    op.drop_index(op.f('ix_crm_realtor_files_file_source_id'), table_name='realtor_files', schema='crm')
    op.drop_index(op.f('ix_crm_realtor_files_created_by'), table_name='realtor_files', schema='crm')
    op.drop_index(op.f('ix_crm_realtor_files_assigned_to'), table_name='realtor_files', schema='crm')
    op.drop_table('realtor_files', schema='crm')
    op.drop_index(op.f('ix_crm_landlord_files_file_source_id'), table_name='landlord_files', schema='crm')
    op.drop_index(op.f('ix_crm_landlord_files_created_by'), table_name='landlord_files', schema='crm')
    op.drop_index(op.f('ix_crm_landlord_files_assigned_to'), table_name='landlord_files', schema='crm')
    op.drop_table('landlord_files', schema='crm')
    op.drop_index(op.f('ix_crm_file_texts_created_by'), table_name='file_texts', schema='crm')
    op.drop_table('file_texts', schema='crm')
    op.drop_index(op.f('ix_crm_file_calls_created_by'), table_name='file_calls', schema='crm')
    op.drop_table('file_calls', schema='crm')
    op.drop_table('file_statuses', schema='crm')
    op.drop_table('file_sources', schema='crm')
    op.drop_table('file_labels', schema='crm')
    # ### end Alembic commands ###
