"""label_ids

Revision ID: a1ad0a5725be
Revises: f0e31040b1f1
Create Date: 2025-10-13 18:09:39.061688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ad0a5725be'
down_revision: Union[str, None] = 'f0e31040b1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('label_ids', sa.ARRAY(sa.BigInteger()), nullable=True), schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'label_ids', schema='account')
    # ### end Alembic commands ###
