"""discount_code_length

Revision ID: a555ffe5721b
Revises: 3d22e77410b2
Create Date: 2025-05-31 18:01:53.004876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a555ffe5721b'
down_revision: Union[str, None] = '3d22e77410b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True,
               schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discounts', 'code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               schema='financial')
    # ### end Alembic commands ###
