"""realtor_fix

Revision ID: a59f02a2c7a3
Revises: a115009334fb
Create Date: 2025-07-30 18:13:36.648234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59f02a2c7a3'
down_revision: Union[str, None] = 'a115009334fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtor_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtor_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='crm')
    # ### end Alembic commands ###
