"""added saved ads

Revision ID: a72e9f8c42ae
Revises: e38bee6ad86f
Create Date: 2024-09-15 16:09:03.893806

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a72e9f8c42ae"
down_revision: Union[str, None] = "e38bee6ad86f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_ads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ad_id", sa.BigInteger(), nullable=True),
        sa.Column("ad_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.alter_column(
        "property_wanted_ads",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        schema="advertisement",
    )


def downgrade() -> None:
    op.alter_column(
        "property_wanted_ads",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        schema="advertisement",
    )
    op.drop_table("saved_ads", schema="account")
    # ### end Alembic commands ###
