"""change foreign key of users.avata and contract.pdf files to new files table

Revision ID: a9cf95bd03d9
Revises: 6b940c144af4
Create Date: 2024-09-18 13:27:39.969837

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9cf95bd03d9"
down_revision: Union[str, None] = "6b940c144af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_avatar_file_id_fkey", "users", schema="account", type_="foreignkey")
    # op.create_foreign_key(
    #     None, "users", "files_", ["avatar_file_id"], ["id"], source_schema="account", referent_schema="shared"
    # )
    op.drop_constraint("contracts_pdf_file_id_fkey", "contracts", schema="contract", type_="foreignkey")
    # op.create_foreign_key(
    #     None, "contracts", "files_", ["pdf_file_id"], ["id"], source_schema="contract", referent_schema="shared"
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contracts", schema="contract", type_="foreignkey")
    op.create_foreign_key(
        "contracts_pdf_file_id_fkey",
        "contracts",
        "files",
        ["pdf_file_id"],
        ["id"],
        source_schema="contract",
        referent_schema="shared",
    )
    op.drop_constraint(None, "users", schema="account", type_="foreignkey")
    op.create_foreign_key(
        "users_avatar_file_id_fkey",
        "users",
        "files",
        ["avatar_file_id"],
        ["id"],
        source_schema="account",
        referent_schema="shared",
    )
    # ### end Alembic commands ###
