"""second_crm_changes

Revision ID: aca4aa06e5dc
Revises: a6e68fff10b1
Create Date: 2025-08-07 16:21:27.541466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca4aa06e5dc'
down_revision: Union[str, None] = 'a6e68fff10b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crm'
    )
    op.create_index(op.f('ix_crm_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_tasks_created_by'), 'tasks', ['created_by'], unique=False, schema='crm')
    op.add_column('file_calls', sa.Column('status', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('second_mobile', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('kitchen', sa.ARRAY(sa.String()), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('property_characteristics', sa.ARRAY(sa.String()), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('occupancy_status', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('parking_type', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('parking_count', sa.Integer(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('floor', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('units_per_floor', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('total_floors', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('visit_time', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('evacuation_date', sa.Date(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('label_ids', sa.ARRAY(sa.BigInteger()), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('latitude', sa.Float(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('longitude', sa.Float(), nullable=True), schema='crm')
    op.create_index(op.f('ix_crm_landlord_files_city_id'), 'landlord_files', ['city_id'], unique=False, schema='crm')
    op.create_index(op.f('ix_crm_landlord_files_district_id'), 'landlord_files', ['district_id'], unique=False, schema='crm')
    op.create_foreign_key(None, 'landlord_files', 'cities', ['city_id'], ['id'], source_schema='crm', referent_schema='shared')
    op.create_foreign_key(None, 'landlord_files', 'districts', ['district_id'], ['id'], source_schema='crm', referent_schema='shared')
    op.drop_column('landlord_files', 'parking', schema='crm')
    op.create_index(op.f('ix_crm_tenant_files_city_id'), 'tenant_files', ['city_id'], unique=False, schema='crm')
    op.create_foreign_key(None, 'tenant_files', 'cities', ['city_id'], ['id'], source_schema='crm', referent_schema='shared')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_files', schema='crm', type_='foreignkey')
    op.drop_index(op.f('ix_crm_tenant_files_city_id'), table_name='tenant_files', schema='crm')
    op.add_column('landlord_files', sa.Column('parking', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='crm')
    op.drop_constraint(None, 'landlord_files', schema='crm', type_='foreignkey')
    op.drop_constraint(None, 'landlord_files', schema='crm', type_='foreignkey')
    op.drop_index(op.f('ix_crm_landlord_files_district_id'), table_name='landlord_files', schema='crm')
    op.drop_index(op.f('ix_crm_landlord_files_city_id'), table_name='landlord_files', schema='crm')
    op.drop_column('landlord_files', 'longitude', schema='crm')
    op.drop_column('landlord_files', 'latitude', schema='crm')
    op.drop_column('landlord_files', 'label_ids', schema='crm')
    op.drop_column('landlord_files', 'evacuation_date', schema='crm')
    op.drop_column('landlord_files', 'visit_time', schema='crm')
    op.drop_column('landlord_files', 'total_floors', schema='crm')
    op.drop_column('landlord_files', 'units_per_floor', schema='crm')
    op.drop_column('landlord_files', 'floor', schema='crm')
    op.drop_column('landlord_files', 'parking_count', schema='crm')
    op.drop_column('landlord_files', 'parking_type', schema='crm')
    op.drop_column('landlord_files', 'occupancy_status', schema='crm')
    op.drop_column('landlord_files', 'property_characteristics', schema='crm')
    op.drop_column('landlord_files', 'kitchen', schema='crm')
    op.drop_column('landlord_files', 'second_mobile', schema='crm')
    op.drop_column('file_calls', 'status', schema='crm')
    op.drop_index(op.f('ix_crm_tasks_created_by'), table_name='tasks', schema='crm')
    op.drop_index(op.f('ix_crm_tasks_assigned_to'), table_name='tasks', schema='crm')
    op.drop_table('tasks', schema='crm')
    # ### end Alembic commands ###
