"""added visit requests for ads

Revision ID: b0bd87daea52
Revises: fe8474a6cb9b
Create Date: 2024-09-25 12:28:39.465727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bd87daea52'
down_revision: Union[str, None] = 'fe8474a6cb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requester_mobile', sa.String(length=50), nullable=True),
    sa.Column('requester_user_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_mobile', sa.String(length=50), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('advertisement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.BigInteger(), nullable=True),
    sa.Column('rejected_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='advertisement'
    )
    op.create_index(op.f('ix_advertisement_visit_requests_id'), 'visit_requests', ['id'], unique=False, schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisement_visit_requests_id'), table_name='visit_requests', schema='advertisement')
    op.drop_table('visit_requests', schema='advertisement')
    # ### end Alembic commands ###
