"""add_discount_phone

Revision ID: c36ee4456c55
Revises: ec1f8bc3a090
Create Date: 2025-09-28 18:11:24.338372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36ee4456c55'
down_revision: Union[str, None] = 'ec1f8bc3a090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('specified_user_phone', sa.String(length=15), nullable=True), schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'specified_user_phone', schema='financial')
    # ### end Alembic commands ###
