"""fix_property_ads

Revision ID: c6f612c1d7b5
Revises: a555ffe5721b
Create Date: 2025-06-04 16:14:09.195184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f612c1d7b5'
down_revision: Union[str, None] = 'a555ffe5721b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_advertisement_property_ads_id'), 'property_ads', ['id'], unique=False, schema='advertisement')
    op.create_foreign_key(None, 'visit_requests', 'property_ads', ['advertisement_id'], ['id'], source_schema='advertisement', referent_schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_requests', schema='advertisement', type_='foreignkey')
    op.drop_index(op.f('ix_advertisement_property_ads_id'), table_name='property_ads', schema='advertisement')
    # ### end Alembic commands ###
