"""added foreign key to visit requests ad_id

Revision ID: cf67b91f1ba4
Revises: b0bd87daea52
Create Date: 2024-09-25 14:19:22.601167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf67b91f1ba4'
down_revision: Union[str, None] = 'b0bd87daea52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'visit_requests', 'property_ads', ['advertisement_id'], ['id'], source_schema='advertisement', referent_schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_requests', schema='advertisement', type_='foreignkey')
    # ### end Alembic commands ###
