"""realtor_type

Revision ID: d04b5c4da764
Revises: 6c1309b9061e
Create Date: 2025-11-02 12:22:12.668327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04b5c4da764'
down_revision: Union[str, None] = '6c1309b9061e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realtor_files', sa.Column('realtor_type', sa.String(), nullable=True), schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realtor_files', 'realtor_type', schema='crm')
    # ### end Alembic commands ###
