"""user_text

Revision ID: d9b36a285def
Revises: a1ad0a5725be
Create Date: 2025-10-15 12:32:05.000602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b36a285def'
down_revision: Union[str, None] = 'a1ad0a5725be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['account.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='account'
    )
    op.create_index(op.f('ix_account_user_texts_created_by'), 'user_texts', ['created_by'], unique=False, schema='account')
    op.create_index(op.f('ix_account_user_texts_user_id'), 'user_texts', ['user_id'], unique=False, schema='account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_texts_user_id'), table_name='user_texts', schema='account')
    op.drop_index(op.f('ix_account_user_texts_created_by'), table_name='user_texts', schema='account')
    op.drop_table('user_texts', schema='account')
    # ### end Alembic commands ###
