"""remove foreign keys to files table

Revision ID: dbe8a5bf59f5
Revises: 9c00d55df629
Create Date: 2024-10-01 13:11:36.532648

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbe8a5bf59f5"
down_revision: Union[str, None] = "9c00d55df629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None: ...


# ### commands auto generated by Alembic - please adjust! ###
# op.drop_constraint("users_avatar_file_id_fkey", "users", schema="account", type_="foreignkey")
# op.drop_constraint("contracts_pdf_file_id_fkey", "contracts", schema="contract", type_="foreignkey")
# op.drop_constraint(
#     "property_rent_contracts_pdf_file_id_fkey", "property_rent_contracts", schema="contract", type_="foreignkey"
# )
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "property_rent_contracts_pdf_file_id_fkey",
        "property_rent_contracts",
        "files_",
        ["pdf_file_id"],
        ["id"],
        source_schema="contract",
        referent_schema="shared",
    )
    op.create_foreign_key(
        "contracts_pdf_file_id_fkey",
        "contracts",
        "files_",
        ["pdf_file_id"],
        ["id"],
        source_schema="contract",
        referent_schema="shared",
    )
    op.create_foreign_key(
        "users_avatar_file_id_fkey",
        "users",
        "files_",
        ["avatar_file_id"],
        ["id"],
        source_schema="account",
        referent_schema="shared",
    )
    # ### end Alembic commands ###
