"""init database

Revision ID: e38bee6ad86f
Revises:
Create Date: 2024-09-08 14:35:41.748647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e38bee6ad86f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS account")
    op.execute("CREATE SCHEMA IF NOT EXISTS advertisement")
    op.execute("CREATE SCHEMA IF NOT EXISTS contract")
    op.execute("CREATE SCHEMA IF NOT EXISTS financial")
    op.execute("CREATE SCHEMA IF NOT EXISTS shared")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_index(op.f("ix_account_permissions_name"), "permissions", ["name"], unique=True, schema="account")
    op.create_table(
        "discounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("starts_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ends_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("used_counts", sa.Integer(), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("specified_roles", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    op.create_table(
        "files",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bucket", sa.String(length=50), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.create_table(
        "provinces",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_role", sa.String(), nullable=False),
        sa.Column("permission_id", sa.BigInteger(), nullable=False),
        sa.Column("permission_name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["account.permissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_role", "permission_id", name="uq_role_permissions"),
        schema="account",
    )
    op.create_index(
        op.f("ix_account_role_permissions_permission_id"),
        "role_permissions",
        ["permission_id"],
        unique=False,
        schema="account",
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("province_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("lat", sa.String(length=50), nullable=False),
        sa.Column("long", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["shared.provinces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mobile", sa.String(), nullable=False),
        sa.Column("roles", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("national_code", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("father_name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("nick_name", sa.String(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("avatar_file_id", sa.BigInteger(), nullable=True),
        sa.Column("default_city_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["avatar_file_id"],
            ["shared.files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_city_id"],
            ["shared.cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_index(op.f("ix_account_users_mobile"), "users", ["mobile"], unique=True, schema="account")
    op.create_index(op.f("ix_account_users_national_code"), "users", ["national_code"], unique=False, schema="account")
    op.create_table(
        "districts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("lat", sa.String(length=50), nullable=False),
        sa.Column("long", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["shared.cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_role", sa.String(), nullable=False),
        sa.Column("iban", sa.String(), nullable=False),
        sa.Column("owner_name", sa.String(), nullable=False),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("branch_name", sa.String(), nullable=True),
        sa.Column("card_number", sa.String(), nullable=True),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "user_role", "iban", name="uq_bank_account"),
        schema="account",
    )
    op.create_index(
        op.f("ix_account_bank_accounts_user_id"), "bank_accounts", ["user_id"], unique=False, schema="account"
    )
    op.create_index(
        op.f("ix_account_bank_accounts_user_role"), "bank_accounts", ["user_role"], unique=False, schema="account"
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_mobile", sa.String(length=11), nullable=False),
        sa.Column("user_is_active", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("avatar_file_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["avatar_file_id"],
            ["shared.files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_index(
        op.f("ix_account_organizations_user_id"), "organizations", ["user_id"], unique=False, schema="account"
    )
    op.create_index(
        op.f("ix_account_organizations_user_mobile"), "organizations", ["user_mobile"], unique=False, schema="account"
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
        schema="account",
    )
    op.create_index(
        op.f("ix_account_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False, schema="account"
    )
    op.create_table(
        "property_wanted_ads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("districts", sa.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("property_type", sa.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("min_size", sa.INTEGER(), nullable=True),
        sa.Column("room_count", sa.INTEGER(), nullable=True),
        sa.Column("created_by_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("elevator", sa.BOOLEAN(), nullable=True),
        sa.Column("storage_room", sa.BOOLEAN(), nullable=True),
        sa.Column("parking", sa.BOOLEAN(), nullable=True),
        sa.Column("max_deposit", sa.INTEGER(), nullable=True),
        sa.Column("max_rent", sa.INTEGER(), nullable=True),
        sa.Column("sale_price", sa.INTEGER(), nullable=True),
        sa.Column("construction_year", sa.INTEGER(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_reported", sa.BOOLEAN(), nullable=True),
        sa.Column("report_description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["shared.cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix_advertisement_property_wanted_ads_id"),
        "property_wanted_ads",
        ["id"],
        unique=False,
        schema="advertisement",
    )
    op.create_table(
        "swap_ads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("have", sa.Text(), nullable=True),
        sa.Column("want", sa.Text(), nullable=True),
        sa.Column("price", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_by_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_reported", sa.BOOLEAN(), nullable=True),
        sa.Column("report_description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="advertisement",
    )
    op.create_index(op.f("ix_advertisement_swap_ads_id"), "swap_ads", ["id"], unique=False, schema="advertisement")
    op.create_table(
        "contracts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_party_type", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("key", sa.String(length=6), nullable=True),
        sa.Column("password", sa.String(length=8), nullable=True),
        sa.Column("pdf_file_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["account.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pdf_file_id"],
            ["shared.files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contracts_owner_user_id"), "contracts", ["owner_user_id"], unique=False, schema="contract"
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("payer_user_id", sa.BigInteger(), nullable=True),
        sa.Column("payee_user_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("clearing_status", sa.String(length=50), nullable=True),
        sa.Column("initial_amount", sa.BigInteger(), nullable=True),
        sa.Column("paid_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("extra_info", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["payee_user_id"],
            ["account.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    op.create_index(
        op.f("ix_financial_invoices_payee_user_id"), "invoices", ["payee_user_id"], unique=False, schema="financial"
    )
    op.create_index(
        op.f("ix_financial_invoices_payer_user_id"), "invoices", ["payer_user_id"], unique=False, schema="financial"
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_role", sa.String(), nullable=False),
        sa.Column("property_type", sa.String(), nullable=True),
        sa.Column("deed_status", sa.String(), nullable=True),
        sa.Column("deed_image_file_ids", sa.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("registration_area", sa.String(), nullable=True),
        sa.Column("main_register_number", sa.BigInteger(), nullable=True),
        sa.Column("sub_register_number", sa.BigInteger(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("build_year", sa.Integer(), nullable=True),
        sa.Column("is_rebuilt", sa.Boolean(), nullable=True),
        sa.Column("structure_type", sa.String(), nullable=True),
        sa.Column("facade_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("direction_type", sa.String(), nullable=True),
        sa.Column("flooring_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("restroom_type", sa.String(), nullable=True),
        sa.Column("heating_system_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("cooling_system_types", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("kitchen_type", sa.String(), nullable=True),
        sa.Column("water_supply_type", sa.String(), nullable=True),
        sa.Column("electricity_supply_type", sa.String(), nullable=True),
        sa.Column("gas_supply_type", sa.String(), nullable=True),
        sa.Column("sewage_supply_type", sa.String(), nullable=True),
        sa.Column("number_of_rooms", sa.Integer(), nullable=True),
        sa.Column("parking", sa.Boolean(), nullable=True),
        sa.Column("parking_number", sa.Integer(), nullable=True),
        sa.Column("landline", sa.Boolean(), nullable=True),
        sa.Column("landline_number", sa.String(), nullable=True),
        sa.Column("storage_room", sa.Boolean(), nullable=True),
        sa.Column("storage_room_number", sa.Integer(), nullable=True),
        sa.Column("storage_room_area", sa.Float(), nullable=True),
        sa.Column("other_facilities", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="shared",
    )
    op.create_index(
        op.f("ix_shared_properties_owner_user_id"), "properties", ["owner_user_id"], unique=False, schema="shared"
    )
    op.create_index(
        op.f("ix_shared_properties_owner_user_role"), "properties", ["owner_user_role"], unique=False, schema="shared"
    )
    op.create_table(
        "property_ads",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("district_id", sa.BigInteger(), nullable=True),
        sa.Column("property_id", sa.BigInteger(), nullable=True),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("image_file_ids", sa.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("created_by_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("deposit_amount", sa.INTEGER(), nullable=True),
        sa.Column("rent_amount", sa.INTEGER(), nullable=True),
        sa.Column("sale_price", sa.INTEGER(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_by", sa.BigInteger(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_reported", sa.Boolean(), nullable=True),
        sa.Column("report_description", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["shared.cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["shared.districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["shared.properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="advertisement",
    )
    op.create_index(
        op.f("ix_advertisement_property_ads_id"), "property_ads", ["id"], unique=False, schema="advertisement"
    )
    op.create_table(
        "contract_clauses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("clause_name", sa.String(), nullable=False),
        sa.Column("clause_number", sa.Integer(), nullable=False),
        sa.Column("subclause_number", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_editable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_deletable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "contract_id", "clause_number", "subclause_number", "deleted_at", name="uq_contract_clause"
        ),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_clauses_contract_id"),
        "contract_clauses",
        ["contract_id"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "contract_parties",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_role", sa.String(), nullable=False),
        sa.Column("party_type", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("signature_type", sa.String(), nullable=True),
        sa.Column("signature_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_parties_contract_id"),
        "contract_parties",
        ["contract_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_parties_user_id"), "contract_parties", ["user_id"], unique=False, schema="contract"
    )
    op.create_index(
        op.f("ix_contract_contract_parties_user_role"),
        "contract_parties",
        ["user_role"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "contract_payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=True),
        sa.Column("payer_id", sa.BigInteger(), nullable=False),
        sa.Column("payee_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_bulk", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["financial.invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payee_id"],
            ["account.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_payments_contract_id"),
        "contract_payments",
        ["contract_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_payments_invoice_id"),
        "contract_payments",
        ["invoice_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_payments_payee_id"),
        "contract_payments",
        ["payee_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_payments_payer_id"),
        "contract_payments",
        ["payer_id"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "contract_steps",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id", "type", "deleted_at", name="uq_contract_steps"),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_contract_steps_contract_id"),
        "contract_steps",
        ["contract_id"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "property_rent_contracts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("property_id", sa.BigInteger(), nullable=True),
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_party_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("pdf_file_id", sa.BigInteger(), nullable=True),
        sa.Column("property_handover_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("deposit_amount", sa.BigInteger(), nullable=True),
        sa.Column("rent_amount", sa.BigInteger(), nullable=True),
        sa.Column("rent_day", sa.Integer(), nullable=True),
        sa.Column("tenant_bank_account_id", sa.BigInteger(), nullable=True),
        sa.Column("tenant_penalty_fee", sa.BigInteger(), nullable=True),
        sa.Column("landlord_rent_bank_account_id", sa.BigInteger(), nullable=True),
        sa.Column("landlord_deposit_bank_account_id", sa.BigInteger(), nullable=True),
        sa.Column("landlord_penalty_fee", sa.BigInteger(), nullable=True),
        sa.Column("tracking_code_status", sa.String(), nullable=False),
        sa.Column("tracking_code_value", sa.String(), nullable=True),
        sa.Column("tracking_code_generation_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["landlord_deposit_bank_account_id"],
            ["account.bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["landlord_rent_bank_account_id"],
            ["account.bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["account.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pdf_file_id"],
            ["shared.files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["shared.properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_bank_account_id"],
            ["account.bank_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_contract_id"),
        "property_rent_contracts",
        ["contract_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_landlord_deposit_bank_account_id"),
        "property_rent_contracts",
        ["landlord_deposit_bank_account_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_landlord_rent_bank_account_id"),
        "property_rent_contracts",
        ["landlord_rent_bank_account_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_owner_user_id"),
        "property_rent_contracts",
        ["owner_user_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_pdf_file_id"),
        "property_rent_contracts",
        ["pdf_file_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_property_id"),
        "property_rent_contracts",
        ["property_id"],
        unique=False,
        schema="contract",
    )
    op.create_index(
        op.f("ix_contract_property_rent_contracts_tenant_bank_account_id"),
        "property_rent_contracts",
        ["tenant_bank_account_id"],
        unique=False,
        schema="contract",
    )
    op.create_table(
        "invoice_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("extra_info", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["financial.invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    op.create_index(
        op.f("ix_financial_invoice_items_invoice_id"), "invoice_items", ["invoice_id"], unique=False, schema="financial"
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=True),
        sa.Column("gateway", sa.String(length=50), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("authority_code", sa.String(), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["financial.invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    op.create_index(
        op.f("ix_financial_transactions_invoice_id"), "transactions", ["invoice_id"], unique=False, schema="financial"
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("credit", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("bank_account_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["account.bank_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["account.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    op.create_table(
        "cheques",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("payment_id", sa.BigInteger(), nullable=False),
        sa.Column("serial", sa.String(), nullable=False),
        sa.Column("series", sa.String(), nullable=False),
        sa.Column("sayaad_code", sa.String(), nullable=False),
        sa.Column("image_file_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("payee_type", sa.String(), nullable=False),
        sa.Column("payee_national_code", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["contract.contract_payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="contract",
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=True),
        sa.Column("wallet_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["financial.invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["financial.wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="financial",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet_transactions", schema="financial")
    op.drop_table("cheques", schema="contract")
    op.drop_table("wallets", schema="financial")
    op.drop_index(op.f("ix_financial_transactions_invoice_id"), table_name="transactions", schema="financial")
    op.drop_table("transactions", schema="financial")
    op.drop_index(op.f("ix_financial_invoice_items_invoice_id"), table_name="invoice_items", schema="financial")
    op.drop_table("invoice_items", schema="financial")
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_tenant_bank_account_id"),
        table_name="property_rent_contracts",
        schema="contract",
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_property_id"), table_name="property_rent_contracts", schema="contract"
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_pdf_file_id"), table_name="property_rent_contracts", schema="contract"
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_owner_user_id"),
        table_name="property_rent_contracts",
        schema="contract",
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_landlord_rent_bank_account_id"),
        table_name="property_rent_contracts",
        schema="contract",
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_landlord_deposit_bank_account_id"),
        table_name="property_rent_contracts",
        schema="contract",
    )
    op.drop_index(
        op.f("ix_contract_property_rent_contracts_contract_id"), table_name="property_rent_contracts", schema="contract"
    )
    op.drop_table("property_rent_contracts", schema="contract")
    op.drop_index(op.f("ix_contract_contract_steps_contract_id"), table_name="contract_steps", schema="contract")
    op.drop_table("contract_steps", schema="contract")
    op.drop_index(op.f("ix_contract_contract_payments_payer_id"), table_name="contract_payments", schema="contract")
    op.drop_index(op.f("ix_contract_contract_payments_payee_id"), table_name="contract_payments", schema="contract")
    op.drop_index(op.f("ix_contract_contract_payments_invoice_id"), table_name="contract_payments", schema="contract")
    op.drop_index(op.f("ix_contract_contract_payments_contract_id"), table_name="contract_payments", schema="contract")
    op.drop_table("contract_payments", schema="contract")
    op.drop_index(op.f("ix_contract_contract_parties_user_role"), table_name="contract_parties", schema="contract")
    op.drop_index(op.f("ix_contract_contract_parties_user_id"), table_name="contract_parties", schema="contract")
    op.drop_index(op.f("ix_contract_contract_parties_contract_id"), table_name="contract_parties", schema="contract")
    op.drop_table("contract_parties", schema="contract")
    op.drop_index(op.f("ix_contract_contract_clauses_contract_id"), table_name="contract_clauses", schema="contract")
    op.drop_table("contract_clauses", schema="contract")
    op.drop_index(op.f("ix_advertisement_property_ads_id"), table_name="property_ads", schema="advertisement")
    op.drop_table("property_ads", schema="advertisement")
    op.drop_index(op.f("ix_shared_properties_owner_user_role"), table_name="properties", schema="shared")
    op.drop_index(op.f("ix_shared_properties_owner_user_id"), table_name="properties", schema="shared")
    op.drop_table("properties", schema="shared")
    op.drop_index(op.f("ix_financial_invoices_payer_user_id"), table_name="invoices", schema="financial")
    op.drop_index(op.f("ix_financial_invoices_payee_user_id"), table_name="invoices", schema="financial")
    op.drop_table("invoices", schema="financial")
    op.drop_index(op.f("ix_contract_contracts_owner_user_id"), table_name="contracts", schema="contract")
    op.drop_table("contracts", schema="contract")
    op.drop_index(op.f("ix_advertisement_swap_ads_id"), table_name="swap_ads", schema="advertisement")
    op.drop_table("swap_ads", schema="advertisement")
    op.drop_index(
        op.f("ix_advertisement_property_wanted_ads_id"), table_name="property_wanted_ads", schema="advertisement"
    )
    op.drop_table("property_wanted_ads", schema="advertisement")
    op.drop_index(op.f("ix_account_refresh_tokens_user_id"), table_name="refresh_tokens", schema="account")
    op.drop_table("refresh_tokens", schema="account")
    op.drop_index(op.f("ix_account_organizations_user_mobile"), table_name="organizations", schema="account")
    op.drop_index(op.f("ix_account_organizations_user_id"), table_name="organizations", schema="account")
    op.drop_table("organizations", schema="account")
    op.drop_index(op.f("ix_account_bank_accounts_user_role"), table_name="bank_accounts", schema="account")
    op.drop_index(op.f("ix_account_bank_accounts_user_id"), table_name="bank_accounts", schema="account")
    op.drop_table("bank_accounts", schema="account")
    op.drop_table("districts", schema="shared")
    op.drop_index(op.f("ix_account_users_national_code"), table_name="users", schema="account")
    op.drop_index(op.f("ix_account_users_mobile"), table_name="users", schema="account")
    op.drop_table("users", schema="account")
    op.drop_table("cities", schema="shared")
    op.drop_index(op.f("ix_account_role_permissions_permission_id"), table_name="role_permissions", schema="account")
    op.drop_table("role_permissions", schema="account")
    op.drop_table("provinces", schema="shared")
    op.drop_table("files", schema="shared")
    op.drop_table("discounts", schema="financial")
    op.drop_index(op.f("ix_account_permissions_name"), table_name="permissions", schema="account")
    op.drop_table("permissions", schema="account")
    # ### end Alembic commands ###

    # drop schema
    op.execute("DROP SCHEMA account")
    op.execute("DROP SCHEMA advertisement")
    op.execute("DROP SCHEMA contract")
    op.execute("DROP SCHEMA financial")
    op.execute("DROP SCHEMA shared")
