"""sale_file

Revision ID: ec1f8bc3a090
Revises: efeff25bea7b
Create Date: 2025-09-24 10:07:19.886752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1f8bc3a090'
down_revision: Union[str, None] = 'efeff25bea7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord_files', sa.Column('listing_type', sa.String(), nullable=False, server_default='RENT'), schema='crm')
    op.add_column('landlord_files', sa.Column('sale_price', sa.BigInteger(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('sale_payment_method', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('number_of_owners', sa.Integer(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('handover_date', sa.String(), nullable=True), schema='crm')
    op.add_column('landlord_files', sa.Column('deed_status', sa.String(), nullable=True), schema='crm')
    op.add_column('tenant_files', sa.Column('listing_type', sa.String(), nullable=False, server_default='RENT'), schema='crm')
    op.add_column('tenant_files', sa.Column('budget', sa.BigInteger(), nullable=True), schema='crm')
    op.add_column('tenant_files', sa.Column('sale_payment_method', sa.String(), nullable=True), schema='crm')
    op.add_column('tenant_files', sa.Column('expected_date', sa.String(), nullable=True), schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_files', 'expected_date', schema='crm')
    op.drop_column('tenant_files', 'sale_payment_method', schema='crm')
    op.drop_column('tenant_files', 'budget', schema='crm')
    op.drop_column('tenant_files', 'listing_type', schema='crm')
    op.drop_column('landlord_files', 'deed_status', schema='crm')
    op.drop_column('landlord_files', 'handover_date', schema='crm')
    op.drop_column('landlord_files', 'number_of_owners', schema='crm')
    op.drop_column('landlord_files', 'sale_payment_method', schema='crm')
    op.drop_column('landlord_files', 'sale_price', schema='crm')
    op.drop_column('landlord_files', 'listing_type', schema='crm')
    # ### end Alembic commands ###
