"""nullable_fullname

Revision ID: efeff25bea7b
Revises: aca4aa06e5dc
Create Date: 2025-08-17 12:56:53.074787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efeff25bea7b'
down_revision: Union[str, None] = 'aca4aa06e5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landlord_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='crm')
    op.alter_column('tenant_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='crm')
    op.alter_column('landlord_files', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='crm')
    # ### end Alembic commands ###
