"""test

Revision ID: f0e31040b1f1
Revises: 27c874a2744a
Create Date: 2025-10-13 17:32:36.104292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e31040b1f1'
down_revision: Union[str, None] = '27c874a2744a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_labels', sa.Column('type', sa.String(), nullable=False, server_default='FILE'), schema='crm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_labels', 'type', schema='crm')
    # ### end Alembic commands ###
