"""change property_ads description type to text

Revision ID: fb03f0330df5
Revises: 3b7e994d2330
Create Date: 2024-10-07 17:15:17.825785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb03f0330df5'
down_revision: Union[str, None] = '3b7e994d2330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_ads', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True,
               schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_ads', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True,
               schema='advertisement')
    # ### end Alembic commands ###
