"""add dynamic-prices to ads

Revision ID: fbda502caa04
Revises: 5b3f21391c7a
Create Date: 2024-09-23 15:30:00.396248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbda502caa04'
down_revision: Union[str, None] = '5b3f21391c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_ads', sa.Column('dynamic_amounts', sa.Boolean(), nullable=True), schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_ads', 'dynamic_amounts', schema='advertisement')
    # ### end Alembic commands ###
