"""added category to ads

Revision ID: fe8474a6cb9b
Revises: fbda502caa04
Create Date: 2024-09-24 14:10:07.589000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8474a6cb9b'
down_revision: Union[str, None] = 'fbda502caa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_ads', sa.Column('category', sa.String(length=50), nullable=True), schema='advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_ads', 'category', schema='advertisement')
    # ### end Alembic commands ###
