import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, BIGINT

from core.database import SQLALCHEMY_REGISTRY

landlord_files = sa.Table(
    "landlord_files",
    SQLALCHEMY_REGISTRY.metadata,
    sa.Column("id", sa.BigInteger, primary_key=True),
    sa.Column("listing_type", sa.String, nullable=False, default="RENT"),
    sa.Column("file_status", sa.String, nullable=True),
    sa.Column("assigned_to", sa.BigInteger, sa.ForeignKey("account.users.id"), nullable=True, index=True),
    sa.Column("file_source_id", sa.BigInteger, sa.ForeignKey("crm.file_sources.id"), nullable=True, index=True),
    sa.Column("is_realtor", sa.Boolean),
    sa.Column("description", sa.Text),
    sa.Column("mobile", sa.String, nullable=False),
    sa.Column("second_mobile", sa.String),
    sa.Column("full_name", sa.String, nullable=True),
    sa.Column("gender", sa.String),
    sa.Column("rent", sa.BigInteger),
    sa.Column("deposit", sa.BigInteger),
    sa.Column("dynamic_amount", sa.Boolean),
    sa.Column("min_rent", sa.BigInteger),
    sa.Column("max_rent", sa.BigInteger),
    sa.Column("min_deposit", sa.BigInteger),
    sa.Column("max_deposit", sa.BigInteger),
    sa.Column("sale_price", sa.BigInteger),
    sa.Column("sale_payment_method", sa.String),
    sa.Column("number_of_owners", sa.Integer),
    sa.Column("handover_date", sa.String),
    sa.Column("city_id", sa.BigInteger, sa.ForeignKey("shared.cities.id"), nullable=True, index=True),
    sa.Column("district_id", sa.BigInteger, sa.ForeignKey("shared.districts.id"), nullable=True, index=True),
    sa.Column("region", sa.Integer),
    sa.Column("address", sa.Text),
    sa.Column("street", sa.String),
    sa.Column("property_type", sa.String),
    sa.Column("room_count", sa.Integer),
    sa.Column("area", sa.Float),
    sa.Column("build_year", sa.Integer),
    sa.Column("bathroom", sa.ARRAY(sa.String)),
    sa.Column("heating", sa.ARRAY(sa.String)),
    sa.Column("cooling", sa.ARRAY(sa.String)),
    sa.Column("flooring", sa.ARRAY(sa.String)),
    sa.Column("max_tenants", sa.Integer),
    sa.Column("other_facilities", sa.ARRAY(sa.String)),
    sa.Column("kitchen", sa.ARRAY(sa.String)),
    sa.Column("property_characteristics", sa.ARRAY(sa.String)),
    sa.Column("occupancy_status", sa.String),
    sa.Column("parking_type", sa.String),
    sa.Column("parking_count", sa.Integer),
    sa.Column("floor", sa.String),
    sa.Column("units_per_floor", sa.String),
    sa.Column("total_floors", sa.String),
    sa.Column("elevator", sa.Boolean),
    sa.Column("storage", sa.Boolean),
    sa.Column("renovated", sa.Boolean),
    sa.Column("visit_time", sa.String),
    sa.Column("evacuation_date", sa.Date),
    sa.Column("deed_status", sa.String),
    sa.Column("property_image_file_ids", sa.ARRAY(sa.BigInteger)),
    sa.Column("label_ids", ARRAY(BIGINT)),
    sa.Column("monopoly", sa.String),
    sa.Column("landlord_agreed_to_remove_ad", sa.Boolean),
    sa.Column("reason_for_not_removing_ad", sa.Text),
    sa.Column("divar_ad_link", sa.String),
    sa.Column("eitaa_ad_link", sa.String),
    sa.Column("ad_title", sa.String),
    sa.Column("published_on_amline", sa.Boolean),
    sa.Column("amline_ad_id", sa.BigInteger),
    sa.Column("latitude", sa.Float),
    sa.Column("longitude", sa.Float),
    sa.Column("created_at", sa.DateTime(timezone=True), default=sa.func.now()),
    sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now()),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_by", sa.BigInteger, sa.ForeignKey("account.users.id"), nullable=False, index=True),
    schema="crm",
)
