import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, BIGINT

from core.database import SQLALCHEMY_REGISTRY

tenant_files = sa.Table(
    "tenant_files",
    SQLALCHEMY_REGISTRY.metadata,
    sa.Column("id", sa.BigInteger, primary_key=True),
    sa.Column("listing_type", sa.String, nullable=False, default="RENT"),
    sa.Column("file_status", sa.String, nullable=True),
    sa.Column("assigned_to", sa.BigInteger, sa.ForeignKey("account.users.id"), nullable=True, index=True),
    sa.Column("file_source_id", sa.BigInteger, sa.ForeignKey("crm.file_sources.id"), nullable=True, index=True),
    sa.Column("is_realtor", sa.Boolean),
    sa.Column("description", sa.Text),
    sa.Column("mobile", sa.String, nullable=False),
    sa.Column("full_name", sa.String, nullable=True),
    sa.Column("gender", sa.String),
    sa.Column("family_members_count", sa.Integer),
    sa.Column("children_ages_description", sa.Text),
    sa.Column("tenant_deadline", sa.String),
    sa.Column("job", sa.String),
    sa.Column("budget", sa.BigInteger),
    sa.Column("sale_payment_method", sa.String),
    sa.Column("expected_date", sa.String),
    sa.Column("rent", sa.BigInteger),
    sa.Column("deposit", sa.BigInteger),
    sa.Column("dynamic_amount", sa.Boolean),
    sa.Column("min_rent", sa.BigInteger),
    sa.Column("max_rent", sa.BigInteger),
    sa.Column("min_deposit", sa.BigInteger),
    sa.Column("max_deposit", sa.BigInteger),
    sa.Column("payment_method", sa.String),
    sa.Column("city_id", sa.BigInteger, sa.ForeignKey("shared.cities.id"), nullable=True, index=True),
    sa.Column("district_ids", ARRAY(BIGINT)),
    sa.Column("regions", ARRAY(BIGINT)),
    sa.Column("address_description", sa.Text),
    sa.Column("property_type", sa.String),
    sa.Column("room_count", sa.Integer),
    sa.Column("area", sa.Float),
    sa.Column("build_year", sa.Integer),
    sa.Column("bathroom", sa.ARRAY(sa.String)),
    sa.Column("heating", sa.ARRAY(sa.String)),
    sa.Column("cooling", sa.ARRAY(sa.String)),
    sa.Column("flooring", sa.ARRAY(sa.String)),
    sa.Column("other_facilities", sa.ARRAY(sa.String)),
    sa.Column("elevator", sa.Boolean),
    sa.Column("storage", sa.Boolean),
    sa.Column("parking", sa.Boolean),
    sa.Column("ad_title", sa.String),
    sa.Column("eitaa_ad_link", sa.String),
    sa.Column("published_on_amline", sa.Boolean),
    sa.Column("amline_ad_id", sa.BigInteger),
    sa.Column("label_ids", ARRAY(BIGINT)),
    sa.Column("created_at", sa.DateTime(timezone=True), default=sa.func.now()),
    sa.Column("updated_at", sa.DateTime(timezone=True), onupdate=sa.func.now()),
    sa.Column("deleted_at", sa.DateTime(timezone=True)),
    sa.Column("created_by", sa.BigInteger, sa.ForeignKey("account.users.id"), nullable=False, index=True),
    schema="crm",
)
