from dataclasses import dataclass
from . import enums


@dataclass
class Translations:
    data = {
        enums.PartyType.LANDLORD: 'موجر',
        enums.PartyType.TENANT: 'مستاجر',

        enums.PropertyType.APARTMENT_RESIDENTIAL: 'آپارتمان مسکونی',
        enums.PropertyType.APARTMENT_ADMINISTRATIVE: 'آپارتمان اداری',
        enums.PropertyType.APARTMENT_COMMERCIAL: 'آپارتمان تجاری',
        enums.PropertyType.VILLA_RESIDENTIAL: 'ویلایی مسکونی',
        enums.PropertyType.VILLA_ADMINISTRATIVE: 'ویلایی اداری',
        enums.PropertyType.VILLA_COMMERCIAL: 'ویلایی تجاری',
        enums.PropertyType.LAND_ADMINISTRATIVE: 'زمین اداری',
        enums.PropertyType.LAND_COMMERCIAL: 'زمین تجاری',
        enums.PropertyType.LAND_AGRICULTURAL: 'زمین زراعی',
        enums.PropertyType.LAND_GARDEN: 'زمین باغ و باغچه',
        enums.PropertyType.WAREHOUSE_COMMERCIAL: 'انبار تجاری',
        enums.PropertyType.WAREHOUSE_INDUSTRIAL: 'انبار صنعتی',
        enums.PropertyType.HALL_COMMERCIAL: 'سالن تجاری',
        enums.PropertyType.HALL_INDUSTRIAL: 'سالن صنعتی',
        enums.PropertyType.SHED_COMMERCIAL: 'سوله تجاری',
        enums.PropertyType.SHED_INDUSTRIAL: 'سوله صنعتی',
        enums.PropertyType.SHOP: 'مغازه',
        enums.PropertyType.BOOTH: 'غرفه',
        enums.PropertyType.LIVESTOCK: 'دامداری',
        enums.PropertyType.DAIRY_FARM: 'دامپروری',
        enums.PropertyType.POULTRY_FARM: 'مرغداری',
        enums.PropertyType.FISH_FARM: 'پرورش ماهی',
        enums.PropertyType.GREENHOUSE: 'گلخانه',
        enums.PropertyType.FACTORY: 'کارخانه',
        enums.PropertyType.WORKSHOP: 'کارگاه',
        enums.PropertyType.SPORTS: 'ورزشی',
        enums.PropertyType.HEALTHCARE: 'بهداشتی',
        enums.PropertyType.PUBLIC_SERVICE: 'خدمات عمومی',
        enums.PropertyType.PARKING: 'پارکینگ',
        enums.PropertyType.OTHER: 'سایر',

        enums.PropertyDeedStatus.BONYAADI: 'بنیادی',
        enums.PropertyDeedStatus.SHAHRDAARI: 'شهرداری',
        enums.PropertyDeedStatus.ASTAANE_QODS: 'آستان قدس',
        enums.PropertyDeedStatus.SETAADE_EJRAAYI_FARMAAN_EMAAM: 'ستاد اجرای فرمان امام',
        enums.PropertyDeedStatus.DOLATI: 'دولتی',
        enums.PropertyDeedStatus.SHAKHSI: 'شخصی',
        enums.PropertyDeedStatus.OQAAFI: 'اوقافی',
        enums.PropertyDeedStatus.TA_AVONI: 'تعاونی',
        enums.PropertyDeedStatus.BEDOUNE_SANAD: 'بدون سند',
        enums.PropertyDeedStatus.MOQOUFEH_AAM: 'موقوف عام',
        enums.PropertyDeedStatus.MOQOUFEH_KHAAS: 'موقوف خاص',
        enums.PropertyDeedStatus.SHERKATE_SAHAAMIE_KHAAS: 'شرکت سهام خاص',
        enums.PropertyDeedStatus.SHERKATE_SAHAAMIE_AAM: 'شرکت سهام عام',

        enums.PropertyStructureType.BRICK_OR_CINDER_BLOCK: 'آجر یا بلوک سیمانی',
        enums.PropertyStructureType.WITHOUT_SKELETON: 'بدون اسکلت',
        enums.PropertyStructureType.CONCRETE: 'بتونی',
        enums.PropertyStructureType.METAL: 'فلزی',
        enums.PropertyStructureType.CONCRETE_AND_METAL: 'بتونی و فلزی',
        enums.PropertyStructureType.ADOBE_OR_MUD: 'خشتی یا گلی',
        enums.PropertyStructureType.WOODEN: 'چوبی',

        enums.PropertyFacadeType.STONE: 'سنگی',
        enums.PropertyFacadeType.WOOD: 'چوب',
        enums.PropertyFacadeType.BRICK: 'آجر',
        enums.PropertyFacadeType.CLAY_AND_MUD: 'خشت و گل',
        enums.PropertyFacadeType.CEMENT: 'سیمان',
        enums.PropertyFacadeType.COMPOSITE: 'کامپوزیت',
        enums.PropertyFacadeType.ALUMINUM: 'آلومینیوم',
        enums.PropertyFacadeType.GLASS: 'شیشه',
        enums.PropertyFacadeType.STONE_AND_COMPOSITE: 'سنگ و کامپوزیت',
        enums.PropertyFacadeType.STONE_AND_CERAMICS: 'سنگ و سرامیک',
        enums.PropertyFacadeType.CERAMIC: 'سرامیک',
        enums.PropertyFacadeType.TRAVERTINE: 'تراورتن',

        enums.PropertyDirectionType.NORTHERN: 'شمالی',
        enums.PropertyDirectionType.SOUTHERN: 'جنوبی',
        enums.PropertyDirectionType.WESTERN: 'غربی',
        enums.PropertyDirectionType.EASTERN: 'شرقی',

        enums.PropertyFlooringType.LIMIT: 'لیمیت',
        enums.PropertyFlooringType.STONE: 'سنگ',
        enums.PropertyFlooringType.WOOD: 'چوب',
        enums.PropertyFlooringType.PARQUET: 'پارکت',
        enums.PropertyFlooringType.MOSAIC: 'موزاییک',
        enums.PropertyFlooringType.CERAMIC: 'سرامیک',
        enums.PropertyFlooringType.CARPET: 'موکت',
        enums.PropertyFlooringType.CEMENT: 'سیمان',

        enums.PropertyRestroomType.DOES_NOT_HAVE: 'ندارد',
        enums.PropertyRestroomType.IRANI: 'ایرانی',
        enums.PropertyRestroomType.FARANGI: 'فرنگی',
        enums.PropertyRestroomType.BOTH: 'هر دو',

        enums.PropertyHeatingSystemType.FIREPLACE: 'شومینه',
        enums.PropertyHeatingSystemType.HEATER: 'بخاری',
        enums.PropertyHeatingSystemType.TORCH: 'مشعل',
        enums.PropertyHeatingSystemType.CHILLER: 'چیلر',
        enums.PropertyHeatingSystemType.RADIATOR: 'شوفاژ',
        enums.PropertyHeatingSystemType.PACKAGE_UNIT: 'پکیج',
        enums.PropertyHeatingSystemType.OTHER: 'سایر',

        enums.PropertyCoolingSystemType.CHILLER: 'چیلر',
        enums.PropertyCoolingSystemType.WATER_COOLER: 'کولر آبی',
        enums.PropertyCoolingSystemType.AIR_CONDITIONER: 'کولر گازی',
        enums.PropertyCoolingSystemType.OTHER: 'سایر',

        enums.PropertyKitchenType.DOES_NOT_HAVE: 'ندارد',
        enums.PropertyKitchenType.OPEN: 'اپن',
        enums.PropertyKitchenType.STANDARD: 'معمولی',
        enums.PropertyKitchenType.MDF: 'MDF',

        enums.PropertySupplyType.DOES_NOT_HAVE: 'ندارد',
        enums.PropertySupplyType.PUBLIC: 'اشتراکی',
        enums.PropertySupplyType.PRIVATE: 'اختصاصی',

        enums.PropertyFacilitiesType.GAS_STOVE: 'گاز رو میزی',
        enums.PropertyFacilitiesType.JACUZZI: 'جکوزی',
        enums.PropertyFacilitiesType.REMOTE_CONTROLLED_DOOR: 'درب ریموت دار',
        enums.PropertyFacilitiesType.ELECTRIC_SHUTTER: 'کرکره برقی',
        enums.PropertyFacilitiesType.RANGE_HOOD: 'هود',
        enums.PropertyFacilitiesType.SAUNA: 'سونا',
        enums.PropertyFacilitiesType.WATER_WELL: 'چاه آب',
        enums.PropertyFacilitiesType.ANTI_THEFT_DOOR: 'درب ضد سرقت',
        enums.PropertyFacilitiesType.SWIMMING_POOL: 'استخر',
        enums.PropertyFacilitiesType.FURNITURE: 'مبلمان',
        enums.PropertyFacilitiesType.BASEMENT: 'زیرزمین',
        enums.PropertyFacilitiesType.COMMUNITY_HALL: 'سالن اجتماعات',
        enums.PropertyFacilitiesType.CURTAINS: 'پرده',
        enums.PropertyFacilitiesType.LOBBY: 'لابی',
        enums.PropertyFacilitiesType.GREEN_SPACE_AND_FOUNTAIN: 'فضای سبز و آبنما',
        enums.PropertyFacilitiesType.CCTV: 'دوربین مداربسته',
        enums.PropertyFacilitiesType.TERRACE: 'تراس',
        enums.PropertyFacilitiesType.KITCHEN_CABINETS: 'کابینت',
        enums.PropertyFacilitiesType.CARPET_FLOOR: 'کف موکت',
        enums.PropertyFacilitiesType.PRIVATE_YARD: 'حیاط خلوت',
        enums.PropertyFacilitiesType.SPRING_ROOM: 'بهار خواب',
        enums.PropertyFacilitiesType.BALCONY: 'بالکن',
        enums.PropertyFacilitiesType.LIGHTING_SYSTEM: 'سیستم روشنایی',
        enums.PropertyFacilitiesType.JANITOR_CLOSET: 'کمد سرایداری',
        enums.PropertyFacilitiesType.PATIO: 'پاسیو',
        enums.PropertyFacilitiesType.ROOF_WATER_TANK: 'تانکر پشت بام',
        enums.PropertyFacilitiesType.VIDEO_INTERCOM: 'آیفن تصویری',
        enums.PropertyFacilitiesType.WATER_HEATER: 'آب گرم کن',
        enums.PropertyFacilitiesType.CHANDELIER: 'لوستر',

        enums.PaymentType.DEPOSIT: 'رهن',
        enums.PaymentType.RENT: 'اجاره',
        enums.PaymentType.COMMISSION: 'کمیسیون',
        enums.PaymentType.PENALTY: 'جریمه',
        enums.PaymentType.OTHER: 'سایر',

        enums.PaymentMethod.CASH: 'نقد',
        enums.PaymentMethod.CHEQUE: 'چک',

        enums.ChequeCategory.SALARY: 'واریز حقوق',
        enums.ChequeCategory.INSURANCE: 'امور بیمه خدمات',
        enums.ChequeCategory.HEALTH_CARE: 'امور درمانی',
        enums.ChequeCategory.INVESTMENT: 'امور سرمایه گذاری و بورس',
        enums.ChequeCategory.FOREIGN_EXCHANGE: 'امور ارزی در چارچوب ضوابط و مقررات',
        enums.ChequeCategory.LOAN: 'پرداخت قرض و تادیه دیوان (قرض الحسنه, بدهی )',
        enums.ChequeCategory.RETIREMENT: 'امور بازنشستگی',
        enums.ChequeCategory.MOVABLE_PROPERTY: 'معاملات اموال منقول',
        enums.ChequeCategory.IMMOVABLE_PROPERTY: 'معاملات اموال غیر منقول',
        enums.ChequeCategory.CASH_MANAGEMENT: 'مدیریت نقدینگی',
        enums.ChequeCategory.CUSTOMS_DUTIES: 'عوارض گمرکی',
        enums.ChequeCategory.TAX_DUTIES: 'تسویه مالیاتی',
        enums.ChequeCategory.GOVERNMENTAL_SERVICES: 'سایر خدمات دولتی',
        enums.ChequeCategory.FACILITIES: 'تسهیلات و تعهدات',
        enums.ChequeCategory.BAIL_DEPOSIT: 'تودیع وثیقه',
        enums.ChequeCategory.DAILY_EXPENSES: 'هزینه عمومی و امور روزمره',
        enums.ChequeCategory.CHARITY: 'کمک های خیریه',
        enums.ChequeCategory.GOODS_PURCHASE: 'خرید کالا',
        enums.ChequeCategory.SERVICES_PURCHASE: 'خرید خدمات',

        enums.ChequePayeeType.INDIVIDUAL: 'شخص حقیقی',
        enums.ChequePayeeType.LEGAL_ENTITY: 'شخص حقوقی',
        enums.ChequePayeeType.FOREIGN_NATIONALS: 'اتباع',
    }

    @classmethod
    def get(cls, key) -> str:
        return cls.data.get(key, '')
